### ISSUE TITLE
Tags and categories filter

### ISSUE THREAD

**Issue by MsLobster** [dbertella/food-and-quote#6]
How to filter certain tags and categories that I don't want to see on the app?

**Comment by dbertella** [comment]
@MsLobster Tell me a list of categories to include

**Comment by MsLobster** [comment]
starter
side dish
main course
dessert
how to

Now the real question is: if a post contains 1 category to include and 1 category to exclude, how does it work? Does it still appear in the search?

**Comment by dbertella** [comment]
Correct in the next release
